#!/usr/bin/env ruby
# vim: fileencoding=utf-8

# Munin plugin for DodontoF logged-in users count monitoring
#%# family=manual

# Munin プラグインクラス
class MuninPlugin
  # コンストラクタ
  #
  # ブロック付きの場合は内部で config 等を定義することができる
  def initialize(&block)
    @config_proc = Proc.new {}
    @fetch_proc = Proc.new {}

    instance_eval(&block) if block
  end

  # config コマンドで実行する処理を設定する
  # @return [self]
  # @yield config コマンドで実行する処理
  # @yieldparam c [Hash] 設定を格納するハッシュ
  def config(&config_proc)
    @config_proc = config_proc
    self
  end

  # データ取得処理を設定する
  # @return [self]
  # @yield データ取得処理
  # @yieldparam result [Hash] 取得したデータを格納するハッシュ
  def fetch(&fetch_proc)
    @fetch_proc = fetch_proc
    self
  end

  # プラグインの処理を実行する
  def run
    case ARGV.length
    when 0
      begin
        do_fetch
      rescue => fetch_error
        print_error(fetch_error)
        abort
      end

      exit
    when 1
      if ARGV[0] == 'config'
        begin
          do_config
        rescue => config_error
          print_error(config_error)
          abort
        end
      else
        print_usage
        abort
      end
    else
      print_usage
      abort
    end
  end

  private

  def do_config
    config_data = {}

    @config_proc[config_data]

    config_data.each do |k, v|
      puts("#{k} #{v}")
    end
  end

  def do_fetch
    result = {}

    @fetch_proc[result]

    result.each do |k, v|
      puts("#{k}.value #{v}")
    end
  end

  def print_usage
    $stderr.puts("Usage: #{File.basename($PROGRAM_NAME)} [config]")
  end

  def print_error(e)
    $stderr.puts("#{e.class}: #{e}")
  end
end

dodontof_users = MuninPlugin.new do
  @config_dir = ENV['config_dir']
  @config_files = [
    File.join(@config_dir, 'config.rb'),
    File.join(@config_dir, 'config_local.rb')
  ]

  @savedata_dir = ENV['savedata_dir']

  def load_config
    @config_files.each do |config_file|
      begin
        load(config_file)
      rescue LoadError
        # 無視する
      end
    end

    @login_count_path = File.join(@savedata_dir, $loginCountFile)
    @about_max_login_count = $aboutMaxLoginCount
    @limit_login_count = $limitLoginCount
  end

  # ログイン人数を返す
  def get_login_users
    File.read(@login_count_path).to_i
  end

  config do |c|
    load_config

    # graph_configure
    c['graph_title']    = 'DodontoF login users'
    c['graph_category'] = 'DodontoF'
    c['graph_args']     = '--base 1000 --lower-limit 0'
    c['graph_scale']    = 'no'
    c['graph_vlabel']   = 'rooms'
    c['graph_info']     = 'This graph shows number of DodontoF login users.'

    # Create login user tag
    c['LoginUsers.label']    = 'login users'
    c['LoginUsers.type']     = 'GAUGE'
    c['LoginUsers.info']     = 'DodontoF login users'
    c['LoginUsers.draw']     = 'AREA'
    c['LoginUsers.warning']  = @about_max_login_count
    c['LoginUsers.critical'] = @limit_login_count

    # Create about max login tag
    c['AboutMaxLoginCount.label']  = 'about max login'
    c['AboutMaxLoginCount.type']   = 'GAUGE'
    c['AboutMaxLoginCount.info']   = 'DodontoF max login allowance'
    c['AboutMaxLoginCount.draw']   = 'LINE2'
    c['AboutMaxLoginCount.colour'] = 'ff8000'

    # Create limit login tag
    c['LimitLoginCount.label']  = 'limit login'
    c['LimitLoginCount.type']   = 'GAUGE'
    c['LimitLoginCount.info']   = 'DodontoF limit login'
    c['LimitLoginCount.draw']   = 'LINE1'
    c['LimitLoginCount.colour'] = 'ff0000'

    # graph_order
    c['graph_order'] = 'LoginUsers AboutMaxLoginCount LimitLoginCount'
  end

  fetch do |result|
    load_config

    result['LoginUsers']         = get_login_users
    result['AboutMaxLoginCount'] = @about_max_login_count
    result['LimitLoginCount']    = @limit_login_count
  end
end

dodontof_users.run
